### ISSUE TITLE
Exception thrown by repositoryManager.getRepositoryForFile()

### ISSUE THREAD

**Issue by pleymor** [novotnyr/gitlab-quickmr-idea-plugin#30] opened 2020-05-02 11:08 UTC
```
java.lang.Throwable: Do not call synchronous repository update in EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForRoot(VcsRepositoryManager.java:154)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForRoot(VcsRepositoryManager.java:143)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForFile(VcsRepositoryManager.java:102)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForFile(VcsRepositoryManager.java:87)
	at com.intellij.dvcs.repo.AbstractRepositoryManager.getRepositoryForFile(AbstractRepositoryManager.java:63)
	at com.github.novotnyr.idea.git.GitService.getProjectGitUrl(GitService.java:55)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction.getProjectName(CreateMergeRequestAction.java:133)
	at com.github.novotnyr.idea.gitlab.quickmr.CreateMergeRequestAction.actionPerformed(CreateMergeRequestAction.java:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
...
```

**Comment by novotnyr** [comment] 2020-08-25 13:46
Duplicate of #31

**Closed by novotnyr** 2020-08-25 13:46 UTC
Labels: bug
