### ISSUE TITLE
Worked then disappeared

### ISSUE THREAD

**Issue by bsfez** [novotnyr/gitlab-quickmr-idea-plugin#28] opened 2020-02-18 14:36 UTC
I was happy to find this plugin and I could send a merge request twice to a project.
However after that, the submenu item under Git just disappeared.

I deleted the plugin and reinstalled and it was the same.
I deleted the plugin and reinstalled and restarted my computer then it was visible again till I saved my configuration. (gone again)

<img width="1016" alt="Screen Shot 2020-02-18 at 16 35 14 " src="https://user-images.githubusercontent.com/5105929/74745564-c13a7200-526c-11ea-8096-ee8505f260b4.png">

**Comment by novotnyr** [comment] 2020-08-26 08:46
This might happen when assignees are disabled, and **Enable Quick Merge Request to Favourite Assignee** is disabled as well. Since this flow is indeed confusing, it needs to be fixed.

Duplicate of #32

**Closed by novotnyr** 2020-08-26 08:46 UTC
Labels: bug
