### ISSUE TITLE
Error: Failed to create merge request: Cannot invoke "String.length()" because "s" is null

### ISSUE THREAD

**Issue by hirnschmalz** [novotnyr/gitlab-quickmr-idea-plugin#52] opened 2022-08-25 04:41 UTC
Everytime I try to create a MR I get the error message

```
Failed to create merge request: Cannot invoke "String.length()" because "s" is null
```

If I can provide more information please let me know.

**Comment by jbureau-qc** [comment] 2022-11-28 20:04
I am also getting this error on a one computer but not the other one which is quite confusing.

**Comment by novotnyr** [comment] 2023-01-19 22:38
Duplicate of #51.

**Closed** 2023-01-19 22:39 UTC
Labels: duplicate
